### ISSUE TITLE
快速滚动。布局会空白，然后崩溃

### ISSUE THREAD

**Issue by Merbn** [CCY0122/FocusLayoutManager#3]
Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView

**Comment by CCY0122** [comment]
> Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView

请检查你代码中notifyDataSetChanged系列方法调用时机，有没有调用的太早
