### ISSUE TITLE
无限循环滚动效果

### ISSUE THREAD

**Issue by tdxtxt** [CCY0122/FocusLayoutManager#4]
请问如何修改LayoutManager的方式才能达到无限循环滚动呢？
参考demo设置adapter会出现闪烁，我之前是非循环的状态。

**Comment by CCY0122** [comment]
主要是修改adapter，我之前测并没有出现闪烁，能否贴下大致代码

**Comment by tdxtxt** [comment]
非常感谢，demo上的代码，再非循环状态下FocusdPosition位置不是第一个的时候，设置adapter的方式进入循环会闪一下。

我想做效果类似兴业银行首页那种banner，FOCUS_TOP模式，其中RecyclerView高度可折叠，收缩状态下进入循环状态，展开为非循环状态，过程要平滑，所以想借鉴大佬的项目二次修改，如果有更好的方案，求指导一下

**Comment by CCY0122** [comment]
> 非常感谢，demo上的代码，再非循环状态下FocusdPosition位置不是第一个的时候，设置adapter的方式进入循环会闪一下。
> 
> 我想做效果类似兴业银行首页那种banner，FOCUS_TOP模式，其中RecyclerView高度可折叠，收缩状态下进入循环状态，展开为非循环状态，过程要平滑，所以想借鉴大佬的项目二次修改，如果有更好的方案，求指导一下

试试这样：默认开启无限循环，监听收缩状态，当状态为展开时，在onBindViewHolder中根据当前的position和banner数量计算一个endPosition，当滚动到这个endPosition时，return一个空白的布局并停掉recyclerView的scroll能力。
比如你是FOCUS_TOP模式，当已经达到endPosition后，监听滚动方向，如果是向上，我们要手动禁止滚动，这样用户就知道已经滚到末尾了（不知道有没有直接禁止滚动的api，应该可以通过scrollTo(反向滚动值)来抵消掉），而向下的话则不禁止。

**Comment by tdxtxt** [comment]
好的，再次感谢提供思路。
