### ISSUE TITLE
间距问题

### ISSUE THREAD

**Issue by smartsimba** [CCY0122/FocusLayoutManager#5]
![微信图片_20200228134626](https://user-images.githubusercontent.com/11230335/75513792-cf3c7f80-5a30-11ea-99a6-a3dbfc6df7ba.png)

您好，图片在放大的时候，会压缩左边堆叠区域的间距，与右边普通区域的间距不一致，这个问题怎么办呐？

**Comment by CCY0122** [comment]
哈哈哈哈哈无解、、 、item的放大确实会占用间距。
由于在代码设计上 item随着滚动动态的的放大缩小、透明度渐变等动画（依靠TrasitionListener）是可以用户自定义的，也就是说是跟列表布局逻辑互相独立的，所以我当时做的时候就没有对这个现象做特殊处理来适配。。（而且也不好做）

**Comment by smartsimba** [comment]
谢谢回复。我现在找了一个解决方式。目前的放大动画中心点是图片中间，把放大中心点改成右边中间，可以解决图片放票放大压缩图片右边间距。同时layerPadding要改的大一点，我现在改成了24dp。

谢谢您的代码。大大的帮忙解决了这个效果的编码
